// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: office.proto

package tunnel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfficeReq_IpProtocol int32

const (
	OfficeReq_IP  OfficeReq_IpProtocol = 0
	OfficeReq_TCP OfficeReq_IpProtocol = 1
	OfficeReq_UDP OfficeReq_IpProtocol = 2
)

// Enum value maps for OfficeReq_IpProtocol.
var (
	OfficeReq_IpProtocol_name = map[int32]string{
		0: "IP",
		1: "TCP",
		2: "UDP",
	}
	OfficeReq_IpProtocol_value = map[string]int32{
		"IP":  0,
		"TCP": 1,
		"UDP": 2,
	}
)

func (x OfficeReq_IpProtocol) Enum() *OfficeReq_IpProtocol {
	p := new(OfficeReq_IpProtocol)
	*p = x
	return p
}

func (x OfficeReq_IpProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OfficeReq_IpProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_office_proto_enumTypes[0].Descriptor()
}

func (OfficeReq_IpProtocol) Type() protoreflect.EnumType {
	return &file_office_proto_enumTypes[0]
}

func (x OfficeReq_IpProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OfficeReq_IpProtocol.Descriptor instead.
func (OfficeReq_IpProtocol) EnumDescriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{0, 0}
}

type OfficeResp_RespCode int32

const (
	OfficeResp_OK    OfficeResp_RespCode = 0
	OfficeResp_Close OfficeResp_RespCode = 1
	OfficeResp_Deny  OfficeResp_RespCode = 2
)

// Enum value maps for OfficeResp_RespCode.
var (
	OfficeResp_RespCode_name = map[int32]string{
		0: "OK",
		1: "Close",
		2: "Deny",
	}
	OfficeResp_RespCode_value = map[string]int32{
		"OK":    0,
		"Close": 1,
		"Deny":  2,
	}
)

func (x OfficeResp_RespCode) Enum() *OfficeResp_RespCode {
	p := new(OfficeResp_RespCode)
	*p = x
	return p
}

func (x OfficeResp_RespCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OfficeResp_RespCode) Descriptor() protoreflect.EnumDescriptor {
	return file_office_proto_enumTypes[1].Descriptor()
}

func (OfficeResp_RespCode) Type() protoreflect.EnumType {
	return &file_office_proto_enumTypes[1]
}

func (x OfficeResp_RespCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OfficeResp_RespCode.Descriptor instead.
func (OfficeResp_RespCode) EnumDescriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{1, 0}
}

type OfficeReport_ReportEnum int32

const (
	OfficeReport_Test OfficeReport_ReportEnum = 0
	OfficeReport_Full OfficeReport_ReportEnum = 1
	OfficeReport_Bye  OfficeReport_ReportEnum = 2
)

// Enum value maps for OfficeReport_ReportEnum.
var (
	OfficeReport_ReportEnum_name = map[int32]string{
		0: "Test",
		1: "Full",
		2: "Bye",
	}
	OfficeReport_ReportEnum_value = map[string]int32{
		"Test": 0,
		"Full": 1,
		"Bye":  2,
	}
)

func (x OfficeReport_ReportEnum) Enum() *OfficeReport_ReportEnum {
	p := new(OfficeReport_ReportEnum)
	*p = x
	return p
}

func (x OfficeReport_ReportEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OfficeReport_ReportEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_office_proto_enumTypes[2].Descriptor()
}

func (OfficeReport_ReportEnum) Type() protoreflect.EnumType {
	return &file_office_proto_enumTypes[2]
}

func (x OfficeReport_ReportEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OfficeReport_ReportEnum.Descriptor instead.
func (OfficeReport_ReportEnum) EnumDescriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{2, 0}
}

type OfficeIssue_BackPress int32

const (
	OfficeIssue_Free   OfficeIssue_BackPress = 0
	OfficeIssue_Press  OfficeIssue_BackPress = 1
	OfficeIssue_Finnal OfficeIssue_BackPress = 2
)

// Enum value maps for OfficeIssue_BackPress.
var (
	OfficeIssue_BackPress_name = map[int32]string{
		0: "Free",
		1: "Press",
		2: "Finnal",
	}
	OfficeIssue_BackPress_value = map[string]int32{
		"Free":   0,
		"Press":  1,
		"Finnal": 2,
	}
)

func (x OfficeIssue_BackPress) Enum() *OfficeIssue_BackPress {
	p := new(OfficeIssue_BackPress)
	*p = x
	return p
}

func (x OfficeIssue_BackPress) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OfficeIssue_BackPress) Descriptor() protoreflect.EnumDescriptor {
	return file_office_proto_enumTypes[3].Descriptor()
}

func (OfficeIssue_BackPress) Type() protoreflect.EnumType {
	return &file_office_proto_enumTypes[3]
}

func (x OfficeIssue_BackPress) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OfficeIssue_BackPress.Descriptor instead.
func (OfficeIssue_BackPress) EnumDescriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{3, 0}
}

type OfficeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID     uint32               `protobuf:"fixed32,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Sip      uint32               `protobuf:"fixed32,2,opt,name=Sip,proto3" json:"Sip,omitempty"`
	Dip      uint32               `protobuf:"fixed32,3,opt,name=Dip,proto3" json:"Dip,omitempty"`
	Protocol OfficeReq_IpProtocol `protobuf:"varint,4,opt,name=Protocol,proto3,enum=tunnel.OfficeReq_IpProtocol" json:"Protocol,omitempty"`
	Port     uint32               `protobuf:"fixed32,5,opt,name=Port,proto3" json:"Port,omitempty"`
	Data     []byte               `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	Host     string               `protobuf:"bytes,7,opt,name=Host,proto3" json:"Host,omitempty"`
}

func (x *OfficeReq) Reset() {
	*x = OfficeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeReq) ProtoMessage() {}

func (x *OfficeReq) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeReq.ProtoReflect.Descriptor instead.
func (*OfficeReq) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{0}
}

func (x *OfficeReq) GetUUID() uint32 {
	if x != nil {
		return x.UUID
	}
	return 0
}

func (x *OfficeReq) GetSip() uint32 {
	if x != nil {
		return x.Sip
	}
	return 0
}

func (x *OfficeReq) GetDip() uint32 {
	if x != nil {
		return x.Dip
	}
	return 0
}

func (x *OfficeReq) GetProtocol() OfficeReq_IpProtocol {
	if x != nil {
		return x.Protocol
	}
	return OfficeReq_IP
}

func (x *OfficeReq) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *OfficeReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OfficeReq) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type OfficeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status OfficeResp_RespCode `protobuf:"varint,1,opt,name=Status,proto3,enum=tunnel.OfficeResp_RespCode" json:"Status,omitempty"`
	Data   []byte              `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *OfficeResp) Reset() {
	*x = OfficeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeResp) ProtoMessage() {}

func (x *OfficeResp) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeResp.ProtoReflect.Descriptor instead.
func (*OfficeResp) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{1}
}

func (x *OfficeResp) GetStatus() OfficeResp_RespCode {
	if x != nil {
		return x.Status
	}
	return OfficeResp_OK
}

func (x *OfficeResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OfficeReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID      string                  `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Report    OfficeReport_ReportEnum `protobuf:"varint,2,opt,name=Report,proto3,enum=tunnel.OfficeReport_ReportEnum" json:"Report,omitempty"`
	TimeStamp int64                   `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Payload   []byte                  `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *OfficeReport) Reset() {
	*x = OfficeReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficeReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeReport) ProtoMessage() {}

func (x *OfficeReport) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeReport.ProtoReflect.Descriptor instead.
func (*OfficeReport) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{2}
}

func (x *OfficeReport) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *OfficeReport) GetReport() OfficeReport_ReportEnum {
	if x != nil {
		return x.Report
	}
	return OfficeReport_Test
}

func (x *OfficeReport) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *OfficeReport) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OfficeIssue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GWID      string                `protobuf:"bytes,1,opt,name=GWID,proto3" json:"GWID,omitempty"`
	Flag      OfficeIssue_BackPress `protobuf:"varint,2,opt,name=Flag,proto3,enum=tunnel.OfficeIssue_BackPress" json:"Flag,omitempty"`
	TimeStamp int64                 `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Payload   []byte                `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *OfficeIssue) Reset() {
	*x = OfficeIssue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficeIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeIssue) ProtoMessage() {}

func (x *OfficeIssue) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeIssue.ProtoReflect.Descriptor instead.
func (*OfficeIssue) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{3}
}

func (x *OfficeIssue) GetGWID() string {
	if x != nil {
		return x.GWID
	}
	return ""
}

func (x *OfficeIssue) GetFlag() OfficeIssue_BackPress {
	if x != nil {
		return x.Flag
	}
	return OfficeIssue_Free
}

func (x *OfficeIssue) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *OfficeIssue) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_office_proto protoreflect.FileDescriptor

var file_office_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0xe1, 0x01, 0x0a, 0x09, 0x4f, 0x66, 0x66, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x07, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x03, 0x53, 0x69, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x69,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x03, 0x44, 0x69, 0x70, 0x12, 0x38, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x2e, 0x49, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f,
	0x73, 0x74, 0x22, 0x26, 0x0a, 0x0a, 0x49, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x06, 0x0a, 0x02, 0x49, 0x50, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x50, 0x10, 0x02, 0x22, 0x7e, 0x0a, 0x0a, 0x4f, 0x66,
	0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x27, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a,
	0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x44, 0x65, 0x6e, 0x79, 0x10, 0x02, 0x22, 0xbe, 0x01, 0x0a, 0x0c, 0x4f,
	0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12,
	0x37, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1f, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x75, 0x6d,
	0x52, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x29, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x08,
	0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x75, 0x6c, 0x6c,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x79, 0x65, 0x10, 0x02, 0x22, 0xba, 0x01, 0x0a, 0x0b,
	0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x73, 0x73, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x47,
	0x57, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x47, 0x57, 0x49, 0x44, 0x12,
	0x31, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x50, 0x72, 0x65, 0x73, 0x73, 0x52, 0x04, 0x46, 0x6c,
	0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2c, 0x0a, 0x09, 0x42, 0x61,
	0x63, 0x6b, 0x50, 0x72, 0x65, 0x73, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x72, 0x65, 0x65, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x72, 0x65, 0x73, 0x73, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x69, 0x6e, 0x6e, 0x61, 0x6c, 0x10, 0x02, 0x32, 0x7c, 0x0a, 0x09, 0x4f, 0x66, 0x66, 0x69,
	0x63, 0x65, 0x32, 0x47, 0x77, 0x12, 0x33, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x11, 0x2e,
	0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x14, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x4f,
	0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0x13, 0x2e, 0x74, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_office_proto_rawDescOnce sync.Once
	file_office_proto_rawDescData = file_office_proto_rawDesc
)

func file_office_proto_rawDescGZIP() []byte {
	file_office_proto_rawDescOnce.Do(func() {
		file_office_proto_rawDescData = protoimpl.X.CompressGZIP(file_office_proto_rawDescData)
	})
	return file_office_proto_rawDescData
}

var file_office_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_office_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_office_proto_goTypes = []interface{}{
	(OfficeReq_IpProtocol)(0),    // 0: tunnel.OfficeReq.IpProtocol
	(OfficeResp_RespCode)(0),     // 1: tunnel.OfficeResp.RespCode
	(OfficeReport_ReportEnum)(0), // 2: tunnel.OfficeReport.ReportEnum
	(OfficeIssue_BackPress)(0),   // 3: tunnel.OfficeIssue.BackPress
	(*OfficeReq)(nil),            // 4: tunnel.OfficeReq
	(*OfficeResp)(nil),           // 5: tunnel.OfficeResp
	(*OfficeReport)(nil),         // 6: tunnel.OfficeReport
	(*OfficeIssue)(nil),          // 7: tunnel.OfficeIssue
}
var file_office_proto_depIdxs = []int32{
	0, // 0: tunnel.OfficeReq.Protocol:type_name -> tunnel.OfficeReq.IpProtocol
	1, // 1: tunnel.OfficeResp.Status:type_name -> tunnel.OfficeResp.RespCode
	2, // 2: tunnel.OfficeReport.Report:type_name -> tunnel.OfficeReport.ReportEnum
	3, // 3: tunnel.OfficeIssue.Flag:type_name -> tunnel.OfficeIssue.BackPress
	4, // 4: tunnel.Office2Gw.Data:input_type -> tunnel.OfficeReq
	6, // 5: tunnel.Office2Gw.Control:input_type -> tunnel.OfficeReport
	5, // 6: tunnel.Office2Gw.Data:output_type -> tunnel.OfficeResp
	7, // 7: tunnel.Office2Gw.Control:output_type -> tunnel.OfficeIssue
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_office_proto_init() }
func file_office_proto_init() {
	if File_office_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_office_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficeReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficeIssue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_office_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_office_proto_goTypes,
		DependencyIndexes: file_office_proto_depIdxs,
		EnumInfos:         file_office_proto_enumTypes,
		MessageInfos:      file_office_proto_msgTypes,
	}.Build()
	File_office_proto = out.File
	file_office_proto_rawDesc = nil
	file_office_proto_goTypes = nil
	file_office_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// Office2GwClient is the client API for Office2Gw service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Office2GwClient interface {
	Data(ctx context.Context, opts ...grpc.CallOption) (Office2Gw_DataClient, error)
	Control(ctx context.Context, opts ...grpc.CallOption) (Office2Gw_ControlClient, error)
}

type office2GwClient struct {
	cc grpc.ClientConnInterface
}

func NewOffice2GwClient(cc grpc.ClientConnInterface) Office2GwClient {
	return &office2GwClient{cc}
}

func (c *office2GwClient) Data(ctx context.Context, opts ...grpc.CallOption) (Office2Gw_DataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Office2Gw_serviceDesc.Streams[0], "/tunnel.Office2Gw/Data", opts...)
	if err != nil {
		return nil, err
	}
	x := &office2GwDataClient{stream}
	return x, nil
}

type Office2Gw_DataClient interface {
	Send(*OfficeReq) error
	Recv() (*OfficeResp, error)
	grpc.ClientStream
}

type office2GwDataClient struct {
	grpc.ClientStream
}

func (x *office2GwDataClient) Send(m *OfficeReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *office2GwDataClient) Recv() (*OfficeResp, error) {
	m := new(OfficeResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *office2GwClient) Control(ctx context.Context, opts ...grpc.CallOption) (Office2Gw_ControlClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Office2Gw_serviceDesc.Streams[1], "/tunnel.Office2Gw/Control", opts...)
	if err != nil {
		return nil, err
	}
	x := &office2GwControlClient{stream}
	return x, nil
}

type Office2Gw_ControlClient interface {
	Send(*OfficeReport) error
	Recv() (*OfficeIssue, error)
	grpc.ClientStream
}

type office2GwControlClient struct {
	grpc.ClientStream
}

func (x *office2GwControlClient) Send(m *OfficeReport) error {
	return x.ClientStream.SendMsg(m)
}

func (x *office2GwControlClient) Recv() (*OfficeIssue, error) {
	m := new(OfficeIssue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Office2GwServer is the server API for Office2Gw service.
type Office2GwServer interface {
	Data(Office2Gw_DataServer) error
	Control(Office2Gw_ControlServer) error
}

// UnimplementedOffice2GwServer can be embedded to have forward compatible implementations.
type UnimplementedOffice2GwServer struct {
}

func (*UnimplementedOffice2GwServer) Data(Office2Gw_DataServer) error {
	return status.Errorf(codes.Unimplemented, "method Data not implemented")
}
func (*UnimplementedOffice2GwServer) Control(Office2Gw_ControlServer) error {
	return status.Errorf(codes.Unimplemented, "method Control not implemented")
}

func RegisterOffice2GwServer(s *grpc.Server, srv Office2GwServer) {
	s.RegisterService(&_Office2Gw_serviceDesc, srv)
}

func _Office2Gw_Data_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Office2GwServer).Data(&office2GwDataServer{stream})
}

type Office2Gw_DataServer interface {
	Send(*OfficeResp) error
	Recv() (*OfficeReq, error)
	grpc.ServerStream
}

type office2GwDataServer struct {
	grpc.ServerStream
}

func (x *office2GwDataServer) Send(m *OfficeResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *office2GwDataServer) Recv() (*OfficeReq, error) {
	m := new(OfficeReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Office2Gw_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Office2GwServer).Control(&office2GwControlServer{stream})
}

type Office2Gw_ControlServer interface {
	Send(*OfficeIssue) error
	Recv() (*OfficeReport, error)
	grpc.ServerStream
}

type office2GwControlServer struct {
	grpc.ServerStream
}

func (x *office2GwControlServer) Send(m *OfficeIssue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *office2GwControlServer) Recv() (*OfficeReport, error) {
	m := new(OfficeReport)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Office2Gw_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.Office2Gw",
	HandlerType: (*Office2GwServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Data",
			Handler:       _Office2Gw_Data_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Control",
			Handler:       _Office2Gw_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "office.proto",
}
